export default interface IProduct {
    code: String,
    status?: any,
    imported_t?:any,
    url: String,
    creator?: String,
    created_t?: Number,
    last_modified_t?: Number,
    product_name?: String,
    quantity?: String,
    brands?: String,
    categories?: String,
    labels?: String,
    cities?: String,
    purchase_places?: String,
    stores?: String,
    ingredients_text?: String,
    traces?: String,
    serving_size?: String,
    serving_quantity?: Number,
    nutriscore_score?: Number,
    nutriscore_grade?: String,
    main_category?: String,
    image_url?: String,
  }